

#spring:
#  application:
#    name: API-GATEWAY
#  cloud:
#    gateway:
#      routes:
#        - id: USER-SERVICE
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/users/**
#          filters:
#            - StripPrefix=1
#        - id: post-service
#          uri: lb://POST-SERVICE
#          predicates:
#            - Path=/posts/**
#          filters:
#            - StripPrefix=1
#    discovery:
#      locator:
#        enabled: true
#        lower-case-service-id: true

spring:
  config:
    import: optional:configserver:http://localhost:8083/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true



