export const CREATE_COMMENT = "CREATE_COMMENT";
export const GET_POST_COMMENT = "GET_POST_COMMENT";
export const GET_REEL_COMMENT = "GET_REEL_COMMENT";
export const LIKE_COMMENT = "LIKE_COMMENT";
export const UNLIKE_COMMENT = "UNLIKE_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const GET_ALL_COMMENT = "GET_ALL_COMMENT";


// Reel ActionType
export const CREATE_REEL_COMMENT_REQUEST = "CREATE_REEL_COMMENT_REQUEST";
export const CREATE_REEL_COMMENT_SUCCESS = "CREATE_REEL_COMMENT_SUCCESS";
export const CREATE_REEL_COMMENT_FAILURE = "CREATE_REEL_COMMENT_FAILURE";

export const GET_ALL_COMMENTS_REEL_REQUEST = "GET_ALL_COMMENTS_REEL_REQUEST";
export const GET_ALL_COMMENTS_REEL_SUCCESS = "GET_ALL_COMMENTS_REEL_SUCCESS";
export const GET_ALL_COMMENTS_REEL_FAILURE = "GET_ALL_COMMENTS_REEL_FAILURE";

export const DELETE_REEL_COMMENT_REQUEST = "DELETE_REEL_COMMENT_REQUEST";
export const DELETE_REEL_COMMENT_SUCCESS = "DELETE_REEL_COMMENT_SUCCESS";
export const DELETE_REEL_COMMENT_FAILURE = "DELETE_REEL_COMMENT_FAILURE";

export const UPDATE_REEL_COMMENT_REQUEST = "UPDATE_REEL_COMMENT_REQUEST";
export const UPDATE_REEL_COMMENT_SUCCESS = "UPDATE_REEL_COMMENT_SUCCESS";
export const UPDATE_REEL_COMMENT_FAILURE = "UPDATE_REEL_COMMENT_FAILURE";

export const LIKE_REEL_COMMENT_REQUEST = "LIKE_REEL_COMMENT_REQUEST";
export const LIKE_REEL_COMMENT_SUCCESS = "LIKE_REEL_COMMENT_SUCCESS";
export const LIKE_REEL_COMMENT_FAILURE = "LIKE_REEL_COMMENT_FAILURE";

export const DISLIKE_REEL_COMMENT_REQUEST = "DISLIKE_REEL_COMMENT_REQUEST";
export const DISLIKE_REEL_COMMENT_SUCCESS = "DISLIKE_REEL_COMMENT_SUCCESS";
export const DISLIKE_REEL_COMMENT_FAILURE = "DISLIKE_REEL_COMMENT_FAILURE";