export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_BY_USERNAME = "GET_USER_BY_USERNAME";
export const GET_USERS_BY_USER_IDS = "GET_USERS_BY_USER_IDS";
export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const SEARCH_USER = "SEARCH_USER";
export const UPDATE_USER = "UPDATE_USER";

export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAILURE = "SEARCH_USER_FAILURE";

export const FOLLOWER_LIST_REQUEST = "FOLLOWER_LIST_REQUEST";
export const FOLLOWER_LIST_SUCCESS = "FOLLOWER_LIST_SUCCESS";
export const FOLLOWER_LIST_FAILURE = "FOLLOWER_LIST_FAILURE";

export const FOLLOWING_LIST_REQUEST = "FOLLOWING_LIST_REQUEST";
export const FOLLOWING_LIST_SUCCESS = "FOLLOWING_LIST_SUCCESS";
export const FOLLOWING_LIST_FAILURE = "FOLLOWING_LIST_FAILURE";