export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE';
export const FETCH_NOTIFICATIONS_REQUEST = 'FETCH_NOTIFICATIONS_REQUEST';

export const FETCH_UNREAD_COUNT_SUCCESS = 'FETCH_UNREAD_COUNT_SUCCESS';
export const FETCH_UNREAD_COUNT_FAILURE = 'FETCH_UNREAD_COUNT_FAILURE';
export const FETCH_UNREAD_COUNT_REQUEST = 'FETCH_UNREAD_COUNT_REQUEST';

export const DELETE_ALL_NOTIFICATIONS_REQUEST = "DELETE_ALL_NOTIFICATIONS_REQUEST";
export const DELETE_ALL_NOTIFICATIONS_SUCCESS = "DELETE_ALL_NOTIFICATIONS_SUCCESS";
export const DELETE_ALL_NOTIFICATIONS_FAILURE = "DELETE_ALL_NOTIFICATIONS_FAILURE";

export const DELETE_A_NOTIFICATION_REQUEST = "DELETE_A_NOTIFICATION_REQUEST";
export const DELETE_A_NOTIFICATION_SUCCESS = "DELETE_A_NOTIFICATION_SUCCESS";
export const DELETE_A_NOTIFICATION_FAILURE = "DELETE_A_NOTIFICATION_FAILURE";